### ISSUE TITLE
Custom Tile Source & SVG Overlay

### ISSUE THREAD

**Issue by Kampii** [openseadragon/svg-overlay#6]
Hi,

How come SVG overlay does not work when I use custom tile source definition like shown in this example (https://openseadragon.github.io/examples/tilesource-custom/)?

I have prepared some samples to illustrate the problem and here (http://www.c-ev.com/osdragon/regulartilesource.php) you can see the regular definition of the tile source, and here (http://www.c-ev.com/osdragon/customtilesource.php) you can see the custom tile definition version. The svg overlay is lost in the latter and I have no clue why..

**Comment by iangilman** [comment]
In the second example, you're specifying a pixel width for the image, but not a viewport width for where it should appear. Because of that, it defaults to a viewport width of 1. Since your overlay is positioned at 3964x2742, of course it's not visible. To specify both the pixel width and the viewport width, do it like so: 

```
this.viewer = OpenSeadragon({
    id: "contentDiv",
    prefixUrl: "openseadragon-bin-2.0.0/images/",
    tileSources:   {
        width: 10800,
        y: 0,
        x: 0,        
        tileSource: {
            height: 4912,
            width:  7360,
            tileSize: 256,
            getTileUrl: function( level, x, y ){
                return "http://www.c-ev.com/osdragon/svgtest_files/"+level+"/"+x+"_"+y+".png";
                //return "http://www.c-ev.com/osdragon/tile.php?did=5&zid="+level+"_"+x+"_"+y;
            }            
        }
    }
});
```

The outer object passed into `tileSources` is the TiledImage specification, which works in viewport coordinates. The inner object passed as the `tileSource` property of the TiledImage specification is the TileSource specification. 

For historical reasons we allow you to skip the TiledImage specification and just pass a TileSource specification into the `tileSources` property, but I can see how that causes confusion.

**Comment by Kampii** [comment]
Worked like a charm. Thank you a lot!
